/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(aprs2inet.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d2a6b310f963b666db37eeaa021f9fbe)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ax25/aprs2inet.h>
// pydoc.h is automatically generated in the build directory
#include <aprs2inet_pydoc.h>

void bind_aprs2inet(py::module& m)
{

    using aprs2inet    = ::gr::ax25::aprs2inet;


    py::class_<aprs2inet, gr::block, gr::basic_block,
        std::shared_ptr<aprs2inet>>(m, "aprs2inet", D(aprs2inet))

        .def(py::init(&aprs2inet::make),
           py::arg("sample_rate"),
           py::arg("debug_level"),
           D(aprs2inet,make)
        )
        



        ;




}







