/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ax25decode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(48890fcc165eb554bde048a3f09b5317)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ax25/ax25decode.h>
// pydoc.h is automatically generated in the build directory
#include <ax25decode_pydoc.h>

void bind_ax25decode(py::module& m)
{

    using ax25decode    = ::gr::ax25::ax25decode;


    py::class_<ax25decode, gr::block, gr::basic_block,
        std::shared_ptr<ax25decode>>(m, "ax25decode", D(ax25decode))

        .def(py::init(&ax25decode::make),
           py::arg("sample_rate"),
           py::arg("debug_level") = 5,
           D(ax25decode,make)
        )
        



        ;




}







